### ISSUE TITLE
Comment correction Circuit 14 line 172

### ISSUE THREAD

**Issue by RowleyCowper** [sparkfun/SIK-Guide-Code#15]
Hi,

I am just getting back into the coding game after a long absence, but looking at the code description for _shiftWrite_  and referring to the datasheet for the HC595 I think the latching description below is incorrect - by my understanding of the datasheet, the latch actually activates on the **low-to-high** transition rather than the **high-to-low**.  Am I correct?

> // Once the data is in the shift register, we still need to
>   // make it appear at the outputs. We'll toggle the state of
>   // the latchPin, which will signal the shift register to "latch"
>   // the data to the outputs. (Latch activates on the **high-to
>   // -low** transition).

Thank you for your time.
Rowley

**Comment by ToniCorinne** [comment]
Thanks for catching that! The clock pin is actually the high-to-low transition while you are correct that it the latch pin transitions from low-to-high.

**Comment by RowleyCowper** [comment]
You are welcome :)  Have a lovely weekend
