### ISSUE TITLE
missing squiggle bracket

### ISSUE THREAD

**Issue by changokun** [sparkfun/SIK-Guide-Code#19]
SIK-Guide-Code/SIK_circuit14_shiftRegister/SIK_circuit14_shiftRegister.ino
line 90

**Comment by ToniCorinne** [comment]
@bboyho Take a look at this and see if it's still valid. Thanks!

**Comment by bboyho** [comment]
Yeah, it looks like it is missing the curly bracket in the v3.3 circuit 14 example => [ [https://github.com/sparkfun/SIK-Guide-Code/blob/v33/SIK_circuit14_shiftRegister/SIK_circuit14_shiftRegister.ino#L90](https://github.com/sparkfun/SIK-Guide-Code/blob/v33/SIK_circuit14_shiftRegister/SIK_circuit14_shiftRegister.ino#L90) . I'm not sure how to fix the code in an older branch now that we have SIK v4.0a?

**Comment by ToniCorinne** [comment]
@changokun This issue affects the repo code at [tag v3.3](https://github.com/sparkfun/SIK-Guide-Code/tree/v33), but we have updated the code now to[ v4.0](https://github.com/sparkfun/SIK-Guide-Code/tree/v40), so this is a non-issue. Closing this out.
