### ISSUE TITLE
Misspelled Word

### ISSUE THREAD

**Issue by bboyho** [sparkfun/SIK-Guide-Code#20]
I was briefly looking through the "edu_rework" branched repository and noticed a misspelled word. "Therimin" should be spelled "Theremin" here => [https://github.com/sparkfun/SIK-Guide-Code/tree/edu_rework/Project13_Therimin](https://github.com/sparkfun/SIK-Guide-Code/tree/edu_rework/Project13_Therimin) .

Is that what was meant?

**Comment by mgrusin** [comment]
You're right, that should indeed be spelled "theremin." Kudos for your knowledge of antique electronic musical instruments! We'll fix it. Have a great day!
